#!/bin/bash

echo "🔍 Docker Hub OAuth Token Issue Diagnosis"
echo "=========================================="

echo ""
echo "❌ Current Error:"
echo "failed to fetch oauth token: 401 Unauthorized"
echo ""

echo "This error means:"
echo "✅ Docker login succeeded initially"
echo "✅ Docker build completed successfully"
echo "❌ Push failed due to OAuth token scope/permissions issue"
echo ""

echo "🔧 Possible Causes & Solutions:"
echo "==============================="
echo ""

echo "1. ❌ Token Permissions Insufficient"
echo "   ├── Current token may only have 'Read' permissions"
echo "   ├── Required: 'Read, Write, Delete' permissions"
echo "   └── Solution: Regenerate token with full permissions"
echo ""

echo "2. ❌ Token Expired or Revoked"
echo "   ├── Token may have been automatically revoked"
echo "   └── Solution: Create a new token"
echo ""

echo "3. ❌ Repository Permissions Issue"
echo "   ├── Token may not have access to youtrack-mcp repository"
echo "   └── Solution: Verify repository access"
echo ""

echo "🔧 Step-by-Step Fix:"
echo "===================="
echo ""

echo "1. CREATE NEW TOKEN with Full Permissions:"
echo "   ├── Go to: https://hub.docker.com/settings/security"
echo "   ├── Click: 'New Access Token'"
echo "   ├── Description: 'GitHub Actions youtrack-mcp FULL'"
echo "   ├── Permissions: Select 'Read, Write, Delete' ✓"
echo "   ├── Click: 'Generate'"
echo "   └── Copy the new token immediately"
echo ""

echo "2. UPDATE GitHub Secret:"
echo "   ├── Go to: https://github.com/tonyzorin/youtrack-mcp/settings/secrets/actions"
echo "   ├── Find: DOCKER_PASSWORD"
echo "   ├── Click: 'Update'"
echo "   ├── Paste: New token with full permissions"
echo "   └── Click: 'Update secret'"
echo ""

echo "3. VERIFY TOKEN LOCALLY (Optional):"
echo "   ├── Run: docker login -u tonyzorin"
echo "   ├── Enter: New token when prompted"
echo "   ├── Test: docker push tonyzorin/youtrack-mcp:test"
echo "   └── Should succeed if token is correct"
echo ""

echo "🎯 Token Requirements Checklist:"
echo "================================"
echo ""
echo "✅ Token must have 'Read, Write, Delete' permissions"
echo "✅ Token must be for username 'tonyzorin'"
echo "✅ Token must have access to 'youtrack-mcp' repository"
echo "✅ Token must not be expired"
echo "✅ Token must be copied exactly (no extra spaces)"
echo ""

echo "⚠️  Common Issues:"
echo "=================="
echo ""
echo "❌ Selecting only 'Read' or 'Read, Write' permissions"
echo "❌ Token created for wrong username"
echo "❌ Token revoked due to security policy"
echo "❌ Copy/paste errors with extra characters"
echo ""

echo "🚀 After Fixing:"
echo "================"
echo ""
echo "1. Update DOCKER_PASSWORD secret with new token"
echo "2. Push any small change to trigger new workflow"
echo "3. Workflow should succeed with proper push permissions"
echo ""

echo "💡 Expected Success Output:"
echo "==========================="
echo ""
echo "✅ Login Succeeded"
echo "✅ Build completed"
echo "✅ Push layers successful"
echo "✅ Image pushed to tonyzorin/youtrack-mcp:0.4.0_wip"
echo "✅ Docker build summary shows success" 