#!/bin/bash

echo "🔐 GitHub Secrets Setup for Docker Hub"
echo "======================================"

echo ""
echo "✅ Docker Hub Token Generated Successfully!"
echo ""
echo "Username: tonyzorin"
echo "Token: [Your Docker Hub access token - dckr_pat_XXXXXXXXXXXX]"
echo ""

echo "📋 GitHub Secrets Configuration:"
echo "================================"
echo ""
echo "Go to: https://github.com/tonyzorin/youtrack-mcp/settings/secrets/actions"
echo ""
echo "1. DOCKER_USERNAME"
echo "   ├── Name: DOCKER_USERNAME"
echo "   └── Value: tonyzorin"
echo ""
echo "2. DOCKER_PASSWORD"
echo "   ├── Name: DOCKER_PASSWORD"
echo "   └── Value: [Your Docker Hub access token from Docker Hub settings]"
echo ""

echo "🔧 Steps to Add Secrets:"
echo "========================"
echo ""
echo "1. Click 'New repository secret' (or 'Update' if exists)"
echo "2. Name: DOCKER_USERNAME"
echo "3. Secret: tonyzorin"
echo "4. Click 'Add secret'"
echo ""
echo "5. Click 'New repository secret' again"
echo "6. Name: DOCKER_PASSWORD"
echo "7. Secret: [Paste your Docker Hub access token here]"
echo "8. Click 'Add secret'"
echo ""

echo "✅ Verification:"
echo "================"
echo ""
echo "After adding secrets, you should see:"
echo "├── DOCKER_USERNAME ✓"
echo "└── DOCKER_PASSWORD ✓"
echo ""

echo "🚀 Next Steps:"
echo "=============="
echo ""
echo "1. Add both secrets to GitHub repository"
echo "2. Push a commit to trigger new workflow"
echo "3. Check GitHub Actions for successful build"
echo "4. Verify Docker image is pushed to Docker Hub"
echo ""

echo "🎯 Expected Success Output:"
echo "==========================="
echo ""
echo "✅ DOCKER_USERNAME secret is configured"
echo "✅ DOCKER_PASSWORD secret is configured"
echo "✅ Log in to Docker Hub"
echo "✅ Login Succeeded"
echo "✅ Test Docker Hub connectivity"
echo "✅ Build and push Docker image"
echo "✅ Docker build completed successfully"
echo ""

echo "📦 Docker Images That Will Be Created:"
echo "======================================"
echo ""
echo "├── tonyzorin/youtrack-mcp:0.4.0_wip (main branch builds)"
echo "├── tonyzorin/youtrack-mcp:[commit-sha] (every commit)"
echo "└── tonyzorin/youtrack-mcp:latest (releases only)"
echo ""

echo "💡 Token Security:"
echo "=================="
echo ""
echo "✅ This token has 'Read, Write, Delete' permissions"
echo "✅ Token is specifically for GitHub Actions"
echo "✅ Token can be revoked anytime from Docker Hub settings"
echo "⚠️  Never commit this token to git repositories"
echo "⚠️  Only use in GitHub Actions secrets"
echo ""
echo "🔐 Your Token Information:"
echo "=========================="
echo ""
echo "Format: dckr_pat_XXXXXXXXXXXXXXXXXXXX"
echo "Use the actual token you generated in Docker Hub"
echo "Copy it exactly as provided (no extra spaces)" 