#!/bin/bash

echo "🔐 Docker Hub Authentication Troubleshooting"
echo "============================================="

echo ""
echo "The GitHub Actions workflow is failing with:"
echo "❌ Error: unauthorized: incorrect username or password"
echo ""

echo "This usually means one of these issues:"
echo ""
echo "1. ❌ Username is incorrect"
echo "   ├── Expected: 'tonyzorin'"
echo "   └── Check: DOCKER_USERNAME secret in GitHub"
echo ""
echo "2. ❌ Token format is incorrect"
echo "   ├── Should be: Access token from Docker Hub (not password)"
echo "   └── Format: Long alphanumeric string (no 'dckr_pat_' prefix needed)"
echo ""
echo "3. ❌ Token permissions are insufficient"
echo "   ├── Required: Read, Write, Delete permissions"
echo "   └── Check: Token settings in Docker Hub"
echo ""
echo "4. ❌ Token copied with extra characters"
echo "   ├── Issue: Extra spaces, newlines, or formatting"
echo "   └── Fix: Copy only the token value"
echo ""

echo "🔧 How to Fix:"
echo "=============="
echo ""
echo "1. Go to Docker Hub: https://hub.docker.com/settings/security"
echo "2. Click 'New Access Token'"
echo "3. Token description: 'GitHub Actions youtrack-mcp'"
echo "4. Access permissions: 'Read, Write, Delete'"
echo "5. Copy the FULL token (it's a long string)"
echo ""
echo "6. Go to GitHub: https://github.com/tonyzorin/youtrack-mcp/settings/secrets/actions"
echo "7. Edit or create DOCKER_PASSWORD secret"
echo "8. Paste ONLY the token (no extra text)"
echo ""

echo "🧪 Test Local Authentication:"
echo "============================="
echo ""
echo "To test if your token works locally:"
echo "1. Run: docker login -u tonyzorin"
echo "2. When prompted for password, paste your access token"
echo "3. Should see: 'Login Succeeded'"
echo ""

echo "📋 Verify GitHub Secrets:"
echo "========================="
echo ""
echo "Go to: https://github.com/tonyzorin/youtrack-mcp/settings/secrets/actions"
echo ""
echo "DOCKER_USERNAME should be: tonyzorin"
echo "DOCKER_PASSWORD should be: [Your Docker Hub access token]"
echo ""
echo "❗ Common mistakes:"
echo "  - Using Docker Hub password instead of access token"
echo "  - Including 'prodcamp-docker' prefix (should be ONLY the token)"
echo "  - Extra spaces or newlines in the secret"
echo "  - Wrong username (case sensitive)"
echo ""

echo "🔄 After fixing:"
echo "================"
echo "1. Update the GitHub secrets"
echo "2. Push any small change to trigger new workflow"
echo "3. Check the workflow logs for success"
echo ""

echo "💡 The token you provided earlier might need formatting:"
echo "   Original: 'prodcamp-docker Deplete0,Glorifier9,Causation0,Raisin6,Cotton6,Campfire4,Providing0,Bankroll1,Prefix1,Napkin4'"
echo "   DOCKER_USERNAME: tonyzorin"
echo "   DOCKER_PASSWORD: Should be ONLY the access token from Docker Hub"
echo ""
echo "   ⚠️  The format suggests this might not be a standard Docker Hub token."
echo "   Please create a new access token from Docker Hub directly." 